### PR TITLE
Rename atta to rg-cli

### PR DESCRIPTION
**Pull request by Lee-W**
#27

### CODE REVIEW

**Comment by tai271828** [comment]
Wow. Thanks for the quick refactoring. Nitpicking: git comment message `feat(report_generator): reanme atta to report_generator` typo: `rename`.

**Comment by tai271828** [comment]
I will review this pull request in more details when I have a moment. Please wait.

**Comment by Lee-W** [comment]
> Wow. Thanks for the quick refactoring. Nitpicking: git comment message `feat(report_generator): reanme atta to report_generator` typo: `rename`.

Thanks! I've fixed it.

**Comment by tai271828** [comment]
For now we have https://github.com/tai271828/attendees-analyzer/pull/29 . In order to enjoy the CI, let's land this pull request first and iterate minor fixes for the code if any.

**Pull request merged**
